### ISSUE TITLE
大佬，请教问题

### ISSUE THREAD

**Issue by zgsxhcyxd** [vcaesar/gse-bleve#4]
现在有个问题，一个mapping里，有可能有中文文本，也有可能有英文，也有可能中英文都有，现在需求是，就像MySQL 的like查找一样，筛选所有包含的，找了好多分词工具，都没达到想要的效果，您这块有啥建议吗？或者说有没有推荐的结局方案

<sub>Sent from <a href="https://apps.apple.com/cn/app/id1314212521">PPHub</a></sub>

**Comment by vcaesar** [comment]
First, you should speak English.
Gse has many text segment mode and option, and mysql "like" is search engine feature, like WildcardQuery and PrefixQuery.
