### ISSUE TITLE
Update bleve to newest

### ISSUE THREAD

**Issue by ABOB9** [vcaesar/gse-bleve#6]
**can't compile**

/go/pkg/mod/github.com/vcaesar/gse-bleve@v0.33.0/analyzer.go:25:9: invalid composite literal type analysis.Analyzer
/go/pkg/mod/github.com/vcaesar/gse-bleve@v0.33.0/analyzer.go:30:39: cannot use analyzerConstructor (value of type func(config map[string]interface{}, cache *registry.Cache) (*analysis.Analyzer, error)) as type registry.AnalyzerConstructor in argument to registry.RegisterAnalyzer
/go/pkg/mod/github.com/vcaesar/gse-bleve@v0.33.0/analyzer.go:31:42: cannot use analyzerConstructor (value of type func(config map[string]interface{}, cache *registry.Cache) (*analysis.Analyzer, error)) as type registry.AnalyzerConstructor in argument to registry.RegisterAnalyzer

**Compilation finished with exit code 2**

**Comment by vcaesar** [comment]
Closing is due to can't reproduce.

**Comment by tsingsun** [comment]
I think this cause by  the bleve/v2 above 2.3.2;

[bleeve 2.3.5](https://github.com/blevesearch/bleve/releases/tag/v2.3.5) 
Breaking change in defining custom analyzers

**Comment by leopku** [comment]
Any update for compatable with latest bleve?
